kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: db
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: thin
  volumeMode: Filesystem
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: db
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: thin
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi